{% set name = "pyzstd" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf15a39cb3c9b662775e22ffa8c4da09fdde6a15ece5e0ed710b6d3b4329cf36

build:
  number: 0
  script: {{ PYTHON }} -m pip install --install-option="--dynamic-link-zstd" -vv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - zstd ==1.5.0
  run:
    - python

test:
  source_files:
    - tests/
  commands:
    - python -m unittest -v

about:
  home: https://github.com/animalize/pyzstd
  doc_url: https://pyzstd.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings to Zstandard (zstd) compression library
  description: |
    Pyzstd module provides classes and functions for compressing and decompressing data, using Facebook's Zstandard (or zstd as short name) algorithm. The API is similar to Python's bz2/lzma/zlib module.

extra:
  recipe-maintainers:
    - animalize
