{% set name = "pyzstd" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d84271f8baa66c419204c1dd115a4dec8b266f8a2921da21b81764fa208c1db6

build:
  number: 1
  script: {{ PYTHON }} -m pip install --config-settings="--build-option=--dynamic-link-zstd" -vv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - zstd
  run:
    - python
    - typing-extensions >=4.13.2  # [py<313]

test:
  source_files:
    - tests/
  commands:
    - python -m unittest -v

about:
  home: https://github.com/Rogdham/pyzstd
  doc_url: https://pyzstd.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings to Zstandard (zstd) compression library
  description: |
    Pyzstd module provides classes and functions for compressing and decompressing data, using Facebook's Zstandard (or zstd as short name) algorithm. The API style is similar to Python's bz2/lzma/zlib modules.

extra:
  recipe-maintainers:
    - rogdham
