{% set name = "pyzstd" %}
{% set version = "0.15.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32a1b67d5340d8df381e718a788417455edd76bed7e8a4cbd259acdc30b5e17e

build:
  number: 0
  script: {{ PYTHON }} -m pip install --config-settings="--build-option=--dynamic-link-zstd" -vv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - zstd
  run:
    - python

test:
  source_files:
    - tests/
  commands:
    - python -m unittest -v

about:
  home: https://github.com/animalize/pyzstd
  doc_url: https://pyzstd.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings to Zstandard (zstd) compression library
  description: |
    Pyzstd module provides classes and functions for compressing and decompressing data, using Facebook's Zstandard (or zstd as short name) algorithm. The API style is similar to Python's bz2/lzma/zlib modules.

extra:
  recipe-maintainers:
    - animalize
