{% set name = "pyzstd" %}
{% set version = "0.19.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44e7b9be7b445aac742003ddee52ca31385d52dffb8c60adf633fad8e795f10d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - backports.zstd >=1.0.0
    - typing-extensions >=4.13.2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pyzstd
  source_files:
    - tests/
  commands:
    - pip check
    - python -m unittest -v

about:
  home: https://github.com/Rogdham/pyzstd
  doc_url: https://pyzstd.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Support for Zstandard (zstd) compression
  description: |
    Pyzstd module provides classes and functions for compressing and decompressing data, using Facebook's Zstandard (or zstd as short name) algorithm. The API style is similar to Python's bz2/lzma/zlib modules.

extra:
  recipe-maintainers:
    - rogdham
